version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  notifier:
    image: alpine
    depends_on:
      - backend
      - frontend
    command: >
      sh -c 'echo "✅ Backend running at http://localhost:3000/" && echo "✅ Frontend running at http://localhost:5173/"'
